language: python
python:
  - "3.4"
os:
  - linux
sudo: required
dist: trusty
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y python3-gi python3-dbus gir1.2-glib-2.0 libgirepository-1.0-1 libdbus-glib-1-2
install:
    - pip install .
script: bjarkan --help
