language: python
python:
  - "3.4"
os:
  - linux
sudo: required
dist: trusty
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y python-gi-dev python3-dbus
install:
    - pip install .
script: bjarkan --help
