name: bjarkan
version: '0.1.6'
summary: Command line bluetooth utility
description: |
  A command line bluetooth utility that allows you to completely manage all
  things bluetooth. Scanning, pairing, listing of devices.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  bjarkan:
    command: bjarkan

parts:
  bjarkan:
    plugin: python
    stage-packages:
      - gir1.2-gtk-3.0
      - python3-dbus
      - python3-gi
